/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jay_biz_android_handler_jni_NDKTools */

#ifndef _Included_com_jay_biz_android_handler_jni_NDKTools
#define _Included_com_jay_biz_android_handler_jni_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jay_biz_android_handler_jni_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jay_biz_1android_handler_jni_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
